site_url: "https://xhenos.netlify.app"
logo_url: "/cms/assets/logo.svg"
publish_mode: editorial_workflow
media_folder: static/assets
public_folder: /assets/

backend:
  name: github
  repo: xhenos/tachiyomi-website
  branch: gridsome
  open_authoring: true
  squash_merges: true
  use_graphql: true
  commit_messages:
    create: "ðŸš€ Create {{collection}} '{{slug}}'"
    update: "ðŸš€ Update {{collection}} '{{slug}}'"
    delete: "ðŸš€ Delete {{collection}} '{{slug}}'"
    uploadMedia: "ðŸš€ Upload '{{path}}'"
    deleteMedia: "ðŸš€ Delete '{{path}}'"
    openAuthoring: "{{message}}"

collections:
  - name: faq
    label: FAQ
    description: Frequently Asked Questions
    folder: content/help/faq
    extension: md
    format: yaml-frontmatter
    create: false
    slug: "{{slug}}"
    preview_path: "help/faq/{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Body",
          name: "body",
          widget: "markdown",
          buttons: ["bold", "italic", "code", "link", "heading-two", "heading-three", "heading-four", "quote", "bulleted-list", "numbered-list"],
          minimal: true,
        }


  - name: guides
    label: Guides
    label_singular: Guide
    description: User guides
    folder: content/help/guides
    extension: md
    format: yaml-frontmatter
    create: true
    slug: "{{slug}}"
    preview_path: "help/guides/{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Body",
          name: "body",
          widget: "markdown",
          buttons: ["bold", "italic", "code", "link", "heading-two", "heading-three", "heading-four", "quote", "bulleted-list", "numbered-list"],
          minimal: true,
        }


  - name: forks
    label: Forks
    label_singular: Fork
    description: Tachiyomi forks
    folder: content/forks
    extension: md
    format: yaml-frontmatter
    create: false
    slug: "{{slug}}"
    preview_path: "forks/{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Body",
          name: "body",
          widget: "markdown",
          buttons: ["bold", "italic", "code", "link", "heading-two", "heading-three", "heading-four", "quote", "bulleted-list", "numbered-list"],
          minimal: true,
        }

  - name: miscellaneous
    label: Miscellaneous
    description: Miscellaneous files
    files:
      - label: Download
        name: download
        file: content/download/index.md
        preview_path: download/
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: "Body",
              name: "body",
              widget: "markdown",
              buttons: ["bold", "italic", "code", "link", "heading-two", "heading-three", "heading-four", "quote", "bulleted-list", "numbered-list"],
              minimal: true,
            }
      - label: Extensions
        label_singular: Extension
        name: extensions
        file: content/extensions/index.md
        preview_path: extensions/
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: "Body",
              name: "body",
              widget: "markdown",
              buttons: ["bold", "italic", "code", "link", "heading-two", "heading-three", "heading-four", "quote", "bulleted-list", "numbered-list"],
              minimal: true,
            }
      - label: Help
        name: help
        file: content/help/index.md
        preview_path: help/
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: "Body",
              name: "body",
              widget: "markdown",
              buttons: ["bold", "italic", "code", "link", "heading-two", "heading-three", "heading-four", "quote", "bulleted-list", "numbered-list"],
              minimal: true,
            }
      - label: Contribution
        name: contribution
        file: content/help/contribution.md
        preview_path: help/contribution/
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: "Body",
              name: "body",
              widget: "markdown",
              buttons: ["bold", "italic", "code", "link", "heading-two", "heading-three", "heading-four", "quote", "bulleted-list", "numbered-list"],
              minimal: true,
            }
      - label: Sandbox
        name: sandbox
        file: content/sandbox/index.md
        preview_path: sandbox/
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: "Body",
              name: "body",
              widget: "markdown",
              buttons: ["bold", "italic", "code", "link", "heading-two", "heading-three", "heading-four", "quote", "bulleted-list", "numbered-list"],
              minimal: true,
            }
