backend:
  name: github
  repo: xhenos/tachiyomi-website
  branch: gridsome
  open_authoring: true
  commit_messages:
    create: "ğŸš€ Create {{collection}} â€œ{{slug}}â€"
    update: "ğŸš€ Update {{collection}} â€œ{{slug}}â€"
    delete: "ğŸš€ Delete {{collection}} â€œ{{slug}}â€"
    uploadMedia: "ğŸš€ Upload â€œ{{path}}â€"
    deleteMedia: "ğŸš€ Delete â€œ{{path}}â€"
    openAuthoring: "{{message}}"

publish_mode: editorial_workflow

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "faq"
    label: "FAQ"
    folder: "content/help/faq"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "guide"
    label: "Guide"
    folder: "content/help/guides"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "sandbox"
    label: "Sandbox"
    folder: "content/sandbox"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
