site_url: https://xhenos.netlify.app
logo_url: https://xhenos.netlify.app/ogimage.png
publish_mode: editorial_workflow
media_folder: "static"

backend:
  name: github
  repo: xhenos/tachiyomi-website
  branch: gridsome
  open_authoring: true
  squash_merges: true
  commit_messages:
    create: "ğŸš€ Create {{collection}} â€œ{{title}}â€"
    update: "ğŸš€ Update {{collection}} â€œ{{title}}â€"
    delete: "ğŸš€ Delete {{collection}} â€œ{{title}}â€"
    uploadMedia: "ğŸš€ Upload â€œ{{filename}}.{{extension}}â€"
    deleteMedia: "ğŸš€ Delete â€œ{{filename}}.{{extension}}â€"
    openAuthoring: "{{message}}"

collections:
  - name: "faq"
    label: "FAQ"
    description: "Frequently Asked Questions"
    folder: "content/help/faq"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", comment: "Page title and opening header"}
      - {label: "Body", name: "body", widget: "markdown", comment: "Page content"}
  - name: "guide"
    label: "Guide"
    description: "User guides"
    folder: "content/help/guides"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", comment: "Page title and opening header"}
      - {label: "Body", name: "body", widget: "markdown", comment: "Page content"}
  - name: "forks"
    label: "Forks"
    description: "Tachiyomi forks"
    folder: "content/forks"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", comment: "Page title and opening header"}
      - {label: "Body", name: "body", widget: "markdown", comment: "Page content"}
  - name: "sandbox"
    label: "Sandbox"
    description: "Playground area"
    folder: "content/sandbox"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", comment: "Page title and opening header"}
      - {label: "Body", name: "body", widget: "markdown", comment: "Page content"}
