backend:
  name: github
  repo: xhenos/tachiyomi-website
  branch: gridsome
  commit_messages:
    create: "ğŸš€ Create {{collection}} â€œ{{slug}}â€"
    update: "ğŸš€ Update {{collection}} â€œ{{slug}}â€"
    delete: "ğŸš€ Delete {{collection}} â€œ{{slug}}â€"
    uploadMedia: "ğŸš€ Upload â€œ{{path}}â€"
    deleteMedia: "ğŸš€ Delete â€œ{{path}}â€"
    openAuthoring: "{{message}}"

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "MarkdownPage"
    label: "Markdown Page"
    folder: "content"
    create: true
    nested:
      depth: 100
      summary: "{{title}}"
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
